/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Container: typeof import('./../components/layouts/container.vue')['default']
    FontButton: typeof import('./../components/form/FontButton.vue')['default']
    FontTextArea: typeof import('./../components/form/FontTextArea.vue')['default']
    Footer: typeof import('./../components/layouts/footer.vue')['default']
    Header: typeof import('./../components/layouts/header.vue')['default']
    Lang: typeof import('./../components/layouts/lang.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadFont: typeof import('./../components/common/uploadFont.vue')['default']
  }
}
